version: "3"

services:
  server:
    build: "./server"
    volumes:
      - ./server:/app
    ports:
      - 5000:5000
  client:
    build: "./client"
    volumes:
      - ./client:/app
    ports:
      - 8080:80